server:
    port: 8080
    servlet:
        context-path: ${SERVICE_CONTEXT_PATH:/edu}
spring:
    application:
        name: edu-box
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: ${JDBC_URL}
        username: ${JDBC_USERNAME}
        password: ${JDBC_PASSWORD}
    mail:
        host: smtp.gmail.com
        port: 587
        username: manhduc2711@gmail.com
        password: pdpqakyckmcpvvti
        protocol: smtp
        tls: true
        properties:
            mail:
                smtp:
                    auth: true
                    starttls.enable: true
app:
    api:
        ignoring:
            antMatchers: ${API_IGNORING_URL:/login,/registration,/health}



