server:
    port: 8080
    servlet:
        context-path: ${SERVICE_CONTEXT_PATH:/edu}

spring:
    application:
        name: edu-box
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://hcmus.mysql.database.azure.com:3306/edu_box?useSSL=true
        username: hcmus
        password: Edubox123
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        open-in-view: false
    mail:
        host: smtp.gmail.com
        port: 587
        username: manhduc2711@gmail.com
        password: pdpqakyckmcpvvti
        protocol: smtp
        tls: true
        properties:
            mail:
                smtp:
                    auth: true
                    starttls.enable: true
    sql:
        init:
            mode: always
app:
    api:
        ignoring:
            antMatchers: ${API_IGNORING_URL:/login,/registration,/health}




